<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.formssi.bond</groupId>
    <artifactId>dcws-chorflow</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <artifactId>chorflow</artifactId>
  <name>${artifactId}</name>
  <url>http://maven.apache.org</url>
  <description>流程编排</description>

  <dependencies>
    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
      <version>${httpclient5.version}</version>
    </dependency>

    <!--kstry-->
    <dependency>
      <artifactId>kstry-core</artifactId>
      <groupId>cn.kstry.framework</groupId>
      <version>${kstry.version}</version>
    </dependency>


    <!-- 通用工具-->
    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-core</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-doc</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-sms</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-mail</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-redis</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-idempotent</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-mybatis</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-log</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-excel</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-security</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-web</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-ratelimiter</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-translation</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-sensitive</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-encrypt</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-tenant</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-websocket</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>

</project>
