<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.formssi.bond</groupId>
    <artifactId>dcws-modules</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>dcws-ureport2</artifactId>
  <packaging>pom</packaging>
  <name>dcws-ureport2</name>
  <url>http://maven.apache.org</url>

  <description>
    报表模块
  </description>

  <modules>
    <module>ureport2-console</module>
    <module>ureport2-core</module>
    <module>ureport2-font</module>
    <module>ureport2-starter</module>
  </modules>

  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <includes>
          <include>**/*.jar</include>
          <include>**/*.xml</include>
          <include>**/*.xsd</include>
          <include>**/*.schemas</include>
          <include>**/*.handlers</include>
          <include>**/*.properties</include>
          <include>**/*.png</include>
          <include>**/*.jpg</include>
          <include>**/*.gif</include>
          <include>**/*.css</include>
          <include>**/*.js</include>
          <include>**/*.map</include>
          <include>**/*.swf</include>
          <include>**/*.swz</include>
          <include>**/*.html</include>
          <include>**/*.jsp</include>
          <include>**/*.txt</include>
          <include>**/*.eot</include>
          <include>**/*.svg</include>
          <include>**/*.ttf</include>
          <include>**/*.ttc</include>
          <include>**/*.TTF</include>
          <include>**/*.TTC</include>
          <include>**/*.woff</include>
          <include>**/*.woff2</include>
          <include>**/*.md</include>
          <include>**/*.template</include>
        </includes>
      </resource>
      <resource>
        <directory>src/main/java</directory>
        <includes>
          <include>**/*.xml</include>
          <include>**/*.xsd</include>
          <include>**/*.schemas</include>
          <include>**/*.handlers</include>
          <include>**/*.properties</include>
          <include>**/*.png</include>
          <include>**/*.jpg</include>
          <include>**/*.gif</include>
          <include>**/*.css</include>
          <include>**/*.js</include>
          <include>**/*.map</include>
          <include>**/*.html</include>
          <include>**/*.jsp</include>
          <include>**/*.txt</include>
          <include>**/*.eot</include>
          <include>**/*.svg</include>
          <include>**/*.ttf</include>
          <include>**/*.ttc</include>
          <include>**/*.TTF</include>
          <include>**/*.TTC</include>
          <include>**/*.woff</include>
          <include>**/*.woff2</include>
          <include>**/*.md</include>
          <include>**/*.template</include>
        </includes>
      </resource>
    </resources>
  </build>

</project>
