<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.formssi.bond</groupId>
        <artifactId>dcws-common</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>dcws-common-tenant</artifactId>
    <name>dcws-common-tenant</name>
    <url>http://maven.apache.org</url>

    <description>
        dcws-common-tenant 租户模块
    </description>

    <dependencies>

        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>dcws-common-redis</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>dcws-common-mybatis</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>dcws-common-core</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>dcws-common-satoken</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
