<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.formssi.bond</groupId>
    <artifactId>dcws-modules</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>dcws-dashboard</artifactId>
  <name>dcws-dashboard</name>
  <url>http://maven.apache.org</url>

  <description>
    仪表盘模块
  </description>

  <properties>
    <jackson.version.core>2.13.3</jackson.version.core>
    <json.version>20220320</json.version>
    <minio.version>8.2.2</minio.version>
    <commons-net.version>3.6</commons-net.version>
    <commons-dbcp2.version>2.10.0</commons-dbcp2.version>
    <jsch.version>0.1.55</jsch.version>
  </properties>

  <dependencies>
    <!-- web -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <exclusions>
        <exclusion>
          <artifactId>spring-boot-starter-tomcat</artifactId>
          <groupId>org.springframework.boot</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <!-- common-mybatis -->
    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-common-mybatis</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <!-- 数据集 -->
    <dependency>
      <groupId>com.formssi.bond</groupId>
      <artifactId>dcws-dataset-bom</artifactId>
      <scope>compile</scope>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <!-- servlet包 -->
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
    </dependency>
    <!--  jackson  -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>${jackson.version.core}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson.version.core}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>${jackson.version.core}</version>
    </dependency>
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>${json.version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-json-org</artifactId>
      <version>${jackson.version.core}</version>
    </dependency>
  </dependencies>

</project>
