# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8081
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  # undertow 配置
  undertow:
    # HTTP post内容的最大大小。当值为-1时，默认值为大小是无限的
    max-http-post-size: -1
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    # 每块buffer的空间大小,越小的空间被利用越充分
    buffer-size: 512
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 8
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 256

--- # 监控中心配置
spring.boot.admin.client:
  # 增加客户端开关
  enabled: false
  url: http://localhost:9090/admin
#  url: http://10.101.128.5:9090/admin
  instance:
    service-host-type: IP
    metadata:
      username: ${spring.boot.admin.client.username}
      userpassword: ${spring.boot.admin.client.password}
  username: admin
  password: 123456

--- # snail-job 配置
snail-job:
  enabled: false
  # 需要在 SnailJob 后台组管理创建对应名称的组,然后创建任务的时候选择对应的组,才能正确分派任务
  group: "lce_group"
  # SnailJob 接入验证令牌 详见 script/sql/snail_job.sql `sj_group_config` 表
  token: "SJ_cKqBTPzCsWA3VyuCfFoccmuIEGXjr5KT"
  server:
    host: 127.0.0.1
    port: 17888
  # 详见 script/sql/snail_job.sql `sj_namespace` 表
  namespace: ${spring.profiles.active}
  # 随主应用端口飘逸
  port: 2${server.port}

--- # 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # 动态数据源文档 https://www.kancloud.cn/tracy5546/dynamic-datasource/content
    dynamic:
      # 性能分析插件(有性能损耗 不建议生产环境使用)
      p6spy: true
      # 设置默认的数据源或者数据源组,默认值即为 master
      primary: master
      # 严格模式 匹配不到数据源则报错
      strict: true
      datasource:
        # 主库数据源
        master:
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.101.68.29:3306/dcws_dev?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
          username: root
          password: gZsgC4I0!S
        # 从库数据源
        slave:
          lazy: true
          type: ${spring.datasource.type}
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://10.101.68.29:3306/dcws_dev?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&autoReconnect=true&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
          username: root
          password: gZsgC4I0!S

      hikari:
        # 最大连接池数量
        maxPoolSize: 20
        # 最小空闲线程数量
        minIdle: 10
        # 配置获取连接等待超时的时间
        connectionTimeout: 30000
        # 校验超时时间
        validationTimeout: 5000
        # 空闲连接存活最大时间，默认10分钟
        idleTimeout: 600000
        # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认30分钟
        maxLifetime: 1800000
        # 多久检查一次连接的活性
        keepaliveTime: 30000

--- # redis 单机配置(单机与集群只能开启一个另一个需要注释掉)
spring.data:
  redis:
    # 地址
    #    host: 127.0.0.1
    host: 10.101.68.29
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # redis 密码必须配置
    password: FCfY5su9
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl.enabled: false

# redisson 配置
redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # Netty线程池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    # 客户端名称
    clientName: ${lce.name}
    # 最小空闲连接数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 连接空闲超时，单位：毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位：毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptionConnectionPoolSize: 50

--- # mail 邮件发送
mail:
  enabled: true
  #host: smtp.163.com
  host: smtp.qiye.163.com
  #port: 465
  port: 994
  # 是否需要用户名密码验证
  auth: true
  # 发送方，遵循RFC-822标准
  from: yangqingheng@formssi.com
  # 用户名（注意：如果使用foxmail邮箱，此处user为qq号）
  user: yangqingheng@formssi.com
  # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，详情查看相关帮助）
  pass: 2P9QcWZpGBsDTBCQ
  # 使用 STARTTLS安全连接，STARTTLS是对纯文本通信协议的扩展。
  starttlsEnable: true
  # 使用SSL安全连接
  sslEnable: true
  # SMTP超时时长，单位毫秒，缺省值不超时
  timeout: 0
  # Socket连接超时值，单位毫秒，缺省值不超时
  connectionTimeout: 0

--- # sms 短信 支持 阿里云 腾讯云 云片 等等各式各样的短信服务商
# https://sms4j.com/doc3/ 差异配置文档地址 支持单厂商多配置，可以配置多个同时使用
sms:
  # 配置源类型用于标定配置来源(interface,yaml)
  config-type: yaml
  # 用于标定yml中的配置是否开启短信拦截，接口配置不受此限制
  restricted: true
  # 短信拦截限制单手机号每分钟最大发送，只对开启了拦截的配置有效
  minute-max: 1
  # 短信拦截限制单手机号每日最大发送量，只对开启了拦截的配置有效
  account-max: 30
  # 以下配置来自于 com.formssi.sms4j.provider.config.BaseConfig类中
  blends:
    # 唯一ID 用于发送短信寻找具体配置 随便定义别用中文即可
    # 可以同时存在两个相同厂商 例如: ali1 ali2 两个不同的阿里短信账号 也可用于区分租户
    config1:
      # 框架定义的厂商名称标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: alibaba
      # 有些称为accessKey有些称之为apiKey，也有称为sdkKey或者appId。
      access-key-id: 您的accessKey
      # 称为accessSecret有些称之为apiSecret
      access-key-secret: 您的accessKeySecret
      signature: 您的短信签名
      sdk-app-id: 您的sdkAppId
    config2:
      # 厂商标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: tencent
      access-key-id: 您的accessKey
      access-key-secret: 您的accessKeySecret
      signature: 您的短信签名
      sdk-app-id: 您的sdkAppId

--- # 三方授权
justauth:
  # 前端外网访问地址
  address: http://localhost:80
#  address: http://10.101.128.5:80
  type:
    maxkey:
      # maxkey 服务器地址
      # 注意 如下均配置均不需要修改 maxkey 已经内置好了数据
      server-url: http://sso.maxkey.top
      client-id: 876892492581044224
      client-secret: x1Y5MTMwNzIwMjMxNTM4NDc3Mzche8
      redirect-uri: ${justauth.address}/social-callback?source=maxkey
    topiam:
      # topiam 服务器地址
      server-url: http://127.0.0.1:1989/api/v1/authorize/y0q************spq***********8ol
      client-id: 449c4*********937************759
      client-secret: ac7***********1e0************28d
      redirect-uri: ${justauth.address}/social-callback?source=topiam
      scopes: [openid, email, phone, profile]
    qq:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=qq
      union-id: false
    weibo:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=weibo
    gitee:
      client-id: 91436b7940090d09c72c7daf85b959cfd5f215d67eea73acbf61b6b590751a98
      client-secret: 02c6fcfd70342980cd8dd2f2c06c1a350645d76c754d7a264c4e125f9ba915ac
      redirect-uri: ${justauth.address}/social-callback?source=gitee
    dingtalk:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=dingtalk
    baidu:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=baidu
    csdn:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=csdn
    coding:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=coding
      coding-group-name: xx
    oschina:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=oschina
    alipay_wallet:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=alipay_wallet
      alipay-public-key: MIIB**************DAQAB
    wechat_open:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=wechat_open
    wechat_mp:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=wechat_mp
    wechat_enterprise:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=wechat_enterprise
      agent-id: 1000002
    gitlab:
      client-id: 10**********6
      client-secret: 1f7d08**********5b7**********29e
      redirect-uri: ${justauth.address}/social-callback?source=gitlab

--- # 资产管理系统三方接口url及token
assets:
  api:
    url: http://10.101.68.29:8000/api/v1/
    token: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiZjRhNDM1MDFmMmFiMWQ1OWRjNzE3NjY5ZWU1MWVkMGE0ZTY2NDA4Mzc2MmY4NmVjNGUxNzU5NTZiN2UyZThlOTM2ZmFjNTNkMWVmODViODUiLCJpYXQiOjE3NDAxMTg2MjcuNDI4OTM2LCJuYmYiOjE3NDAxMTg2MjcuNDI4OTQ2LCJleHAiOjMwMDI0MjI2MjcuNDI2Mjk5LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.VT4tifmGbr9CblfzRiX8xdatgK_VkiD7nWeY7NUZ3n3ww2Gkks1S8L4q7E7a114EgUCEFRyNrNYRrQdFCkV5mh-JqvMMog-89FtWMEdPOCIShtgv-wzgUaUjborBiCM7Ho0nTP3d0ih8-HPL5m8anJfbxjs4pMNo2CZuX82qx7lldzc1i_zc3Hl4W1F89dmM32gQc-CcY9mvWZLT-mmAsrmsNq5HvrHBupscIZwF7XWRWbVwiG5OV4LoniuD-S7r0fU6fr5uNnkJnP5x_UXVUmGOgqwj-SVp37oiGtEYbP5WwHqTGEF8w5GAWdA9qD8FvYP08GtYo53acYAIEMA67t14z-Ey6vHlxiyAtuYra0QFjsmKwHGOZf3DtoLmpFQIGbxdBj-6esWSESARxojkLcKKowGXEzPGVhRj3U9CY-ecRcH1ABGTDGovSArQQT3AiOJJnd6e4Vw-Il-1E257H9bDCA6nCXkcYTEFwgerp5D_d-RVVdBLfp2td-6cVfLv6YfdE8IJ3Nn3i0uhYv9g_-4ULJYHPfGxNGafEUeqdUsPXpMAP42LNCEPJeAmLMtvzheZvOayAsWaepGpLF22TFdPzc0fNEYSss-hHWIcglwPt84agGdevBCvpVVApY5R1UoHS0Uf4IManmCdaqJo_Lz1_3cQdToEEPBTglD8gpQ

#RSA加密密钥
securityKey:
  dcwsPrivateKey: MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDSE/TMlsbf7YvN1SgP9iVRccHpY0O2oy+WHPGUSqaKS8EqGlmSUOwomxgKI5AbJLEoBEAg/GrAT21PlxNo4MXXPmkr4kGFepDq05uDdL79NGmJulCulku91DmR09wGSzWQJ+WMpi+qLG5D9wlej9QzINHc+/zk2IRKpppEnyCdiRbZ0LQ9deoadamVlR+YIUJ0GLB+1Wkw4uWr3PYkCrtDpT6sUdQjkDJgOo5UMR1dBYd8EEOD3VWaDA0njIQStIsDws7CkGsG9k5lsaYT9iGaJiwskI+UMV/YDZpl5yFk2xUruxupK2uqe2bTQOlPzNIg67+/ReQWmbltuHfqzg6jPvnlASrkgS1k6gUiYeriw5NAjxJLt/4fyKFlNSx5f6b8/MdVkUgdRUddS6Ez31BhbRVIFjTUt4mDc7NX9g+7Ux4agrfam/AAaCwzf8ko9mLDiGLXRua2N9DT2PeO/RLSDPxLd7C31iqWQ7I6wlUHl4QD82gsYBsVIijNTZTf2aa/4r74jfaCZpoxNjq6B//tI21YpaLNAGyAEbCERHZ9RJ7C1vG58/26ekwwnFxeRsVsgJfTqYtqfcOrBf5PMqdW2ZIHX2oXFfxxR9UBYvLB3GPiUEwYBx6PhIc/eN6DVK2eYgWpTdr5TDDlaA+Nvk6JUVDpSXtM7bWcNHi2mtVpKQIDAQABAoICAAi9lVIc1N30xXwVKhNN77wNgl6qR2M2M3Dot+FuYLMA12Lf0Um97bF70Hp9g82pT2ilkqB8uBlTxK3K0J8suPaNbXVKtuStlpF6p+4GgbrJvzlgg+JbtP+LMLEBUlZ9sxcSHeIl+PY43oab5OsnC1JsQ2cRIfLIkmqDt4fy4fnD/iwmW5VyDkE3E4z6dSPQgHIRo+hHC1ciHaGyshgKTUPRgIPNbMjlAz+POCRHHdxkskAmchSutRTRewuh9E3N7rnDlXQxa46Q2W6wP0N12myOOYjKI/srubvkxv+F6BUI637UDGDTwmlHtJ3GBd8Q285MWMBF0WliUH2A7xZZJ/EuDZaBnenHamka6SfGiuGFRWT3hb9QJseM126CB5dYzIO2yTSPURmCxUtyn127MM0lx4eKEV5g+w7rTyNSM63JtNc1krUm53ITtIMUFSfOy9HNjj/YdZFMHK760Os9EkfPyC71nvtFbYQ4dvqwFl+cz4uLcIL2GEYO9XsZGddpzaOHHy/8LcguzIFjBqcoze2o4Ynj1qeZDGYqH7bZX5ov/LhULai2S/ArwXaMpO4/AwAxaCZozf/yMpATpzc/x1nmzRjZGrOEhv4Jc2kZxEY0hLxojNclcBAx4Zkn2uY4NFJtfn+Dq8MMNvJRAtEEINJl2/eQKGTbPfm1aE5fo9MhAoIBAQDm1tArwrbfYcvn2Rpa/4ZGGfLEx7pCAo6NgLngutR1R5IXBsOrjw8RJKgkblTC7idKKYfNF3FofWWUPT/Mlx8PTrmDxrnjGLESzt12/47bu7xHQHjFEWwTzzhB5Y7Eo/1wMTI5ozM2L+Y1s3MwMF95eYT7jUERxybo8KIo8qMT/o5CW9soWSLZSkDb95KZguNXHgZBPgdb6Xs1iFJX6CWBL4otScwPUOW8Q8iSB3JoRWdblH+nenX4rEFm7nu6azuJNBQoVdFHsL6rwXSNyDfBIaJolPiwxWnixTd16wu+NzyK6814A4tWgtJLMuK0qekiuxLc3xAbiMwxyvLM1MaRAoIBAQDo+dZDhIqMBQ2bRf8W43gT9JlaCDUKed7EsZ4qieDm/cC6DnYzBZxzeqIyOWMDdEqnDAR70jb8Y0ZHeurOqURgSsBSA6Ac77jAdIW+CInX13Cm1HRE0Phlri7BHd9EkNPnCHn8RMeAtk1iNuiEpDopPtOnUf9pKCR3jh1VmatIwxWN0yH2gColw2ZK0IbkkEm6W/iIWObP0P5hOfcY2cX/w5gPH3prVqviYIkT4uiisiKiDwK1TPKHoCE9TOg9/lBMKnC4VIx6wsjLlkGXSNHmmFND9QVaIYIFA3EkrIe/6JqcXBHxpwLu8b02VtU+d+kjBtXHYJiUmj1fpYwK0jUZAoIBAQCEQC/10lGJO3Nh+k0SM3EPOpCO0srQRLy9LzHPIdrU8lMtZA+4e3arYLAAZ0GiiGT0JUULaFHuBmGrA0hJA4+k6np4l+Mpy5yvZNsW8SU8mJsuyy4l4WxlEQRvJICeAkISA+19fhW6BslCnPPyeNRKOSfKIsxTziBptmuBQDnUG7QPKqctv5uql9L+8yEHWCi9YZM9z7bRnrubGOXsPTE3iTAF8FC7uaJVMRR5LVELki+8FSDpp8xs0uuJeDpkvEjYu4CM91W2V/l1V5laHYpr2MQ+XJL6W6/lXw3+PdJ1gRnrkVsfVhB/WOX4dUfTL8FEx57v8dA9pisun9JpLcIxAoIBAQCX4dCKoczE7cJqGN7tKAwvTkXvSOxzUPIm3viTGOITFRjg8u6h4qWVLzywa3MeXGESuCXwJyKLtZiqnvqXEgiuke0BSrXGR431gcFzGxPqL9yUFmtaNbXKbBy072mPxK8wrfkAukIpqi+WuN8rIfl8zCWlrjJJds8XVgHPvWfJ/sx9ckhw8CsKBXIZkgpu1ZYLNUw4b2TB1KkR730kqUyIqhXmvgnMEmvqIC8dVM9+yY0Eg66rTWfLfVxOH2ZEjBgDH6Put8gBfBz1hJZsLyAQKfwWkJUVpkSiShUn6IZzWQv6pZdZKB0kc1p8I23P1NKbcChMW6/9KPSb90vt/g55AoIBAGBDYS9FpsfsyYTYQSR5+Udj1puTldise3k19dcX5FAo68vmZpsg81quioIz+Q4xzjyCP8YynlvvqWSal4Ev43tcaOBTVuJY0UsREJlEZI7806jl9oIJaehcENSYwkCSfmgzbQ33i1ZfM+JJjmawjfuHQEjfhixVGK0AC+Qsssgk+tQVjw1iVD6Wdoqttq69Ioib8Tv9783bN1GDCKYi1ekNjVMhdmlGGmPQYnkIdP0TBiwiiOld3Dmvzyi8Khrd4IhxsH4T2NzIxS9aRKwEHOvxUtUbPeqyb4z7FeRQQLMiauCfPkXf0iJ8UDvw9arycPudKUAt8Bipd1hfBlzAeVQ=
  llPublicKey: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAr2wlA5EfxphMQIs85sLWvui8rtArUWaQeUFl0QpEz13RVU2+WZBdbLJ0J8q3t2KSx3r61OJIPnYE3X5/4KzlEZalbMqpTp+cbCQ3ZDctnGSWWiLfoKeBRqjZj2uvc35w6lQ15k58ShK/WOHgEevapAQojGUFykvOYpa4A389XOyRybmSERjBFF2Bn4SiVSmO62Lh3ItveSaiLhgHsjtccY1m+HKP/8+OO3cbnIrXHm7WMDTT6ETKHBRz10u1i6WJIgW5Mt1n4+Mo28egJjcJmQjFrWeLFYEVqqweP9RBDj8t/Rnryan/acc8QrqtuIo4B3OaDKnjAAIrYOxJV98wWB+qB5QV2Jl6870Gq4Fo1+siHxkrEHgVMNyBkNlZWEFRGNMH7sBap7fleEU7vtLtGg/3JSIUYbqgZc07Ommroh2LPCUoVpSsGy8dwd5cwIrML8jqCu8NxGHsIvuVWEY4c8+IAfWFQgisI5zhGVfbmbkb2TgIg2dHXFXrqXnDtUN47ZhmSemcEjVIxSR/vrIgxqoJgsT8dsoLf8qhYvyc2JyDEnfZlLJ3CxvpcKa8OFKrzWF2/6Xe4M1pwhaPskQA+uUKIgSl/Q0jZPayMDQ0y3Tj9PF2x+5Ux1GefG7O1Y1l5W1X7O/jLd9T/1wN+y8UemFS9yh16OHgqurQeo2cNf8CAwEAAQ==