<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.formssi.bond</groupId>
        <artifactId>dcws-modules</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>dcws-system</artifactId>
    <name>dcws-system</name>
    <url>http://maven.apache.org</url>

    <description>
        dcws-system系统模块
    </description>

    <dependencies>

        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>dcws-common-satoken</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-web</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.formssi.bond</groupId>
                    <artifactId>low-code-common-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-mybatis</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-log</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.formssi.bond</groupId>
                    <artifactId>low-code-common-satoken</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-excel</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.formssi.bond</groupId>
                    <artifactId>low-code-common-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-redis</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.formssi.bond</groupId>
                    <artifactId>low-code-common-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-idempotent</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.formssi.bond</groupId>
                    <artifactId>low-code-common-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-translation</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.formssi.bond</groupId>
                    <artifactId>low-code-common-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-sensitive</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-tenant</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.formssi.bond</groupId>
                    <artifactId>low-code-common-satoken</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-oss</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-encrypt</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-sse</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.formssi.bond</groupId>
                    <artifactId>low-code-common-satoken</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.formssi.bond</groupId>
            <artifactId>low-code-common-minio</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>

    </dependencies>
</project>
